### PR TITLE
[web] Fix inconsistencies in storage volumes

### LINKED ISSUE #1108: Inconsistencies in the volumes
Before merging #1104 

not-broken

After merging that pull request

not-not-broken

a) It's not longer possible to add a `/home` volume although it's in the TW configuration
b) The Btrfs switcher is not in sync with the table of volumes

### PR DESCRIPTION
**Pull request by ancorgs**
This fixes #1108, both the problems and the implemented solutions are described there in depth.

Tested manually to check both problems are indeed fixed.

### CODE REVIEW

**Review by dgdavid — APPROVED** [review]
LGTM

File: web/src/components/storage/ProposalPage.jsx [hunk 1]
```diff
@@ -232,6 +232,7 @@ export default function ProposalPage() {
       <ProposalSettingsSection
         availableDevices={state.availableDevices}
         encryptionMethods={state.encryptionMethods}
+        volumeTemplates={state.volumeTemplates}
```
Comment (dgdavid) [inline web/src/components/storage/ProposalPage.jsx:235]: In a talk with @imobachgs, we concluded that this kind of errors could be avoid with the type checking. To do so, the  `volumeTemplates` prop should be required and not have a default value. The consumer is the responsible of giving the empty array if it's the case.

Comment (dgdavid) [reply web/src/components/storage/ProposalPage.jsx:235]: Just a comment for bearing it in mind when activating the ts-check for the whole .jsx files.
